version: "2"
services:
  web:
    env_file:
      - variables.env
    links:
      - db
    environment:
      - POSTGRES_HOST=db
    build: .
    depends_on:
      - db
    ports:
      - "8000:3000"
  db:
    env_file:
      - variables.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    image: postgres
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./data:/var/lib/postgresql/data/pgdata  # mount database file outside